module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: "eslint:recommended",
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    "no-console": "warn",
    "no-unused-vars": "warn",
    "no-undef": "warn",
    "no-multi-spaces": "warn",
    "no-new": "warn",
    "no-var": "warn",
    "prefer-const": "warn",
    "prefer-template": "warn",
    "prefer-arrow-callback": "warn",
    "quote-props": ["warn", "consistent-as-needed"],
    "no-mixed-spaces": "warn",
    "no-tabs": "warn",
    "object-curly-spacing": ["warn", "always"],
    "brace-style": ["warn", "stroustrup"],
    "comma-dangle": ["warn", "always-multiline"],
    "comma-spacing": ["warn", { before: false, after: true }],
    "key-spacing": ["warn", { beforeColon: false, afterColon: true }],
    "no-multiple-empty-lines": "warn",
    "no-trailing-spaces": "warn",
    "no-whitespace-before-property": "warn",
    "no-extra-parens": "warn",
    "no-irregular-whitespace": "warn",
    "no-unexpected-multiline": "warn",
    "no-restricted-syntax": "warn",
    "no-useless-concat": "warn",
    "no-use-before-define": "warn",
    "no-inner-declarations": "warn",
    "no-sequences": "warn",
    "no-unsafe-negation": "warn",
    "no-unsafe-optional-chaining": "warn",
    "no-with-statement": "warn",
    "no-void": "warn",
    "no-unused-expressions": "warn",
    "no-useless-return": "warn",
    "require-await": "warn",
    "require-yield": "warn",
    "vars-on-top": "warn",
    "wrap-iife": "warn",
    strict: "warn",
  },
  overrides: [
    {
      files: ["*.js"],
      env: {
        node: true,
      },
    },
  ],
};
