sonar.projectKey=Weedomeker_decoGestion
sonar.organization=weedomeker

sonar.sources=server/src,client/src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,client/node_modules/**,server/public/**,coverage/**
sonar.coverage.exclusions=test/**,server/public/**
