function createJob(
  client,
  cmd,
  cmd2,
  ville,
  format,
  format2,
  formatPlaque,
  visuel,
  visuel2,
  ref,
  ref2,
  ex,
  visuPath,
  visuPath2,
  writePath,
  jpgName,
  jpgName2,
  perte,
  reg,
  cut,
  teinteMasse,
  stock,
  prodBlanc,
  client2,
) {
  const date = new Date();

  const newJob = {
    _id: Date.now(),
    date: date,
    client: client,
    client2: client2 || client,
    cmd: parseInt(cmd),
    cmd2: cmd2 ? parseInt(cmd2) : 0,
    ville: ville,
    format_visu: format,
    format2_visu: format2,
    format_Plaque: formatPlaque.split("_").pop(),
    visuel: visuel,
    visuel2: visuel2,
    ref: ref,
    ref2: ref2,
    ex: parseInt(ex),
    visuPath: visuPath,
    visuPath2: visuPath2,
    writePath: writePath,
    jpgName: jpgName !== undefined ? jpgName.split("/").slice(2).join("/") + ".jpg" : "",
    jpgName2: jpgName2 !== undefined ? jpgName2.split("/").slice(2).join("/") + ".jpg" : "",
    perte: perte,
    reg: reg,
    cut: cut,
    teinteMasse: teinteMasse,
    useStock: stock,
    prodBlanc: !!prodBlanc,
  };

  return newJob;
}

module.exports = createJob;
